### ISSUE TITLE
Improving accuracy of frequency reported to Sondehub

### ISSUE THREAD

**Issue by eben80** [projecthorus/radiosonde_auto_rx#577] opened 2021-10-10 15:19 UTC
Some of the auto_rx receivers in scanning mode that are reporting to Sondehub seems not to have done frequency calibration and as such they are reporting the wrong frequency back to the Sondehub api.

This means that when we use the sondehub api to request the frequencies for sondes in the area, we are getting also these which show the incorrect frequencies.
One such example where the frequency was actually 400.6MHz:
```
"R5030861": {
    "software_name": "radiosonde_auto_rx",
    "software_version": "1.5.5",
    "uploader_callsign": "XXXX",
    "uploader_position": "XXX",
    "uploader_antenna": "1/4 wave monopole",
    "time_received": "2021-10-10T13:21:00.166403Z",
    "datetime": "2021-10-10T13:21:16.001000Z",
    "manufacturer": "Vaisala",
    "type": "RS41",
    "serial": "R5030861",
    "subtype": "RS41-SGP",
    "frame": 8552,
    "lat": 49.24005,
    "lon": 20.9442,
    "alt": 4700.08129,
    "temp": -12.7,
    "humidity": 80.4,
    "pressure": 573.62,
    "vel_v": -16.9317,
    "vel_h": 4.71026,
    "heading": 343.25841,
    "sats": 10,
    "batt": 2.6,
    "frequency": 400.577,
    "burst_timer": 29909,
    "snr": 15.8,
    "user-agent": "Amazon CloudFront",
    "position": "49.24005,20.9442",
    "upload_time_delta": -1.35,
    "uploader_alt": XXX
  },
```
Is there anything that could be done to rectify this apart from just having the request to calibrate in the installation docs?

**Comment by eben80** [comment] 2021-10-10 20:51
Yes I saw the instructions and I'm not even a user. Would it be an idea to
use the frequency from telemetry for the rs41?

**Comment by eben80** [comment] 2021-10-10 21:05
Oh yes then it will not be available from the start.
It's a functionality in rdzsonde where we query the SondeHub /sondes api
with the receiver coordinates, max range and max age, in return we receive
current reported sondes which are then automatically added to the scan
list. So if the frequency reported to SondeHub is incorrect, you sit with
duplicate entries for the same sonde potentially, with one having the wrong
frequency.

**Comment by darksidelemm** [comment] 2021-10-10 21:06
Well, it's certainly something I can look into. It should be possible to add the frequency reported by the sonde into the JSON output from the decoder once it is available. This may be true for other radiosonde types too.

**Comment by mwheeler-ep** [comment] 2021-10-10 21:22
🤔 we might be able to make an ttgo specific endpoint on sondehub that reports the frequency which has the most reports rather than the current method

**Comment by eben80** [comment] 2021-10-10 21:30
That would work well for areas with sufficient receivers yes. Anything that
can be done closer to the source of the problem will of course help the
areas with less receivers.

**Comment by LukePrior** [comment] 2021-10-12 03:22
You could add an option to the auto rx configuration file to disable uploading the frequency so that users with these bad receivers could continue to upload telemetry but not introduce these errors.

**Comment by darksidelemm** [comment] 2021-10-12 03:29
The problem is that the users who are uploading the bad information don't know they are doing it, so this won't really help.

**Comment by LukePrior** [comment] 2021-10-12 03:31
Oh yeah absolutely more just so when contacting stations you can offer a simple solution instead of needing to purchase a new dongle or taking the station offline.

You could also make frequency uploading disabled by default until the user enables it with a message about needing a correct dongle for future versions.

**Comment by darksidelemm** [comment] 2021-11-11 00:08
This has been added for RS41, RS92 and iMS-100 sondes in auto_rx 1.5.7. I'm not sure if any other radiosonde types report frequency information in their telemetry, so I'm going to close this issue.
If there is any other information available for other sonde types, please re-open this issue.

**Closed by darksidelemm** 2021-11-11 00:08 UTC

**Comment by eben80** [comment] 2021-11-11 05:41
All good. Thank you for this.
